language: go
go:
  - 1.11.x
  - 1.12.x

notifications:
  email: false

install:
  - export GO111MODULE=on
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
